apiVersion: v1
kind: ImageStream
metadata:
  name: mynginx
spec:
  tags:
  - from:
      kind: DockerImage
      name: public.ecr.aws/y6a3u3z2/mynginx:latest
    name: latest
    importPolicy:
      scheduled: true