apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels:
      app: mynginx
spec:
  containers:
    - name: mynginx
      image: image-registry.openshift-image-registry.svc:5000/batur/mynginx:mytag
      ports:
        - containerPort: 8080
          name: "http-server"
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx
  labels:
    app: mynginx
spec:
  ports:
    - port: 8080
      name: web
  clusterIP: None
  selector:
    app: mynginx