apiVersion: v1
kind: Pod
metadata:
  name: kafdrop
  labels:
    app: kafdrop
spec:
  containers:
    - name: kafdrop
      image: obsidiandynamics/kafdrop
      ports:
        - containerPort: 9000
          name: web
      env:
        - name: KAFKA_BROKERCONNECT
          value: kafka-service:9092
        - name: SERVER_SERVLET_CONTEXTPATH
          value: "/"
        - name: KAFKA_ISSECURED
          value: "false"
        - name:  JVM_OPTS
          value: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    - name : kafkacat
      image: confluentinc/cp-kafkacat
      command: ["/bin/sh"]
      args: ["-c", "trap : TERM INT; sleep infinity & wait"]

  restartPolicy: Always