apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server-data
  labels:
    app: nfs-server
spec:
  storageClassName: thin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi