apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server-data
  labels:
    app: nfs-server
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  hostPath:
    path: "/mnt/data"
