kind: Pod
apiVersion: v1
metadata:
  name: pod-using-nfs2
spec:
  securityContext:
    privileged: true
  containers:
    - name: app
      image: ubuntu
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /var/nfs/dates.txt; sleep 5; done"]