apiVersion: v1
kind: Pod
metadata:
  name: cit
  labels:
    app: cit
spec:
  containers:
    - name: cit
      image: nexus.mydomain.com/myproject-cit-service
      env:
      - name: myproject_WEB_URL_POSTFIX
        value: "-myproject.rm.x:9450"
      - name: myproject_REDIS_HOSTNAME
        value: "redis-cluster"
      - name: myproject_SPRING_DATA_MONGODB_URI
        value: "mongodb://admin:myproject@mongo-service:27017/myproject"
      - name: myproject_SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://postgres:5432/demopostgresdb"
      - name: myproject_WEB_JWT_PUBLICKEY
        value: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgWJlGuAxgXXWV7tqyYME9Q0OXqeioB2qQcUYWBWBG+Xv+XCn7lPCG3D9HoYa23KXWE0OSbHPkHI/AZlUaZ7pCog9AhqSroV0D9B+vUcf/YqkuXQ6sw2pGwdoippY55DzCXHNJKBYCGlEduJfEru9hNTfjYj9XPE78qGk4DdCnxcARKH90HhXc4z4bz1JehhXnKRBk5x1OSTwOpvKWXTZ9wCHDhYWvIW4svoN/G4tvcngLGbNY9u8OzmUS1A1qmVDY1vqKmlm1Gr7ZaxvcNMjil0xV/g3DFTR31TCQfdJGRaIU8nvteaIQmShv3/ADQc2TwTTiPb8IbUztO1iltZv8wIDAQAB"
      - name: myproject_WEB_URL_SCHEME
        value: "http"
      - name: myproject_NEXUS_NPM_REGISTRY
        value: "http://192.168.2.51:8081/repository/npm/"
      - name: myproject_REDIS_PORT
        value: "6379"
      - name: myproject_HOST
        value: "myproject.rm.x"
      - name: myproject_WEB_CORS_ORIGIN
        value: "*"
      - name: myproject_PROJECT_NAME
        value: "myproject"
      - name: myproject_SPRING_DATASOURCE_USERNAME
        value: "postgres"
      - name: myproject_SPRING_DATASOURCE_PASSWORD
        value: "94509450"
      - name: myproject_WEB_URL_HOST_POSTFIX
        value: "-myproject.rm.x"
      - name: myproject_SPRING_KAFKA_BOOTSTRAP_SERVERS
        value: "kafka-service:9092"
      - name: myproject_WEB_URL_PREFIX
        value: "http://"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
